"""empty message

Revision ID: 4377314fbe6a
Revises: 79cc26094d3f
Create Date: 2024-02-03 13:30:16.426520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4377314fbe6a'
down_revision = '79cc26094d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.alter_column('companions',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.alter_column('companions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
