"""first commit

Revision ID: 75fbe323e8ca
Revises: 
Create Date: 2023-12-28 21:01:11.458098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fbe323e8ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('grow_time', sa.Integer(), nullable=False),
    sa.Column('harvest_num', sa.Integer(), nullable=False),
    sa.Column('harvest_per', sa.Integer(), nullable=False),
    sa.Column('companions', sa.String(), nullable=False),
    sa.Column('sun_pref', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('crop_name')
    )
    op.create_table('growers',
    sa.Column('grower_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('grower_name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('plantings',
    sa.Column('planting_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('planted_dt', sa.String(), nullable=True),
    sa.Column('harvestable_when', sa.String(), nullable=True),
    sa.Column('companioned', sa.Boolean(), nullable=True),
    sa.Column('light_match', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crop_name'], ['crops.crop_name'], ),
    sa.PrimaryKeyConstraint('planting_id')
    )
    op.create_table('plots',
    sa.Column('grid_value', sa.String(), nullable=False),
    sa.Column('x', sa.NUMERIC(precision=2, scale=0), nullable=False),
    sa.Column('y', sa.NUMERIC(precision=2, scale=0), nullable=False),
    sa.Column('plot_owner', sa.String(), nullable=True),
    sa.Column('plot_contents', sa.Integer(), nullable=True),
    sa.Column('sun', sa.String(length=15), nullable=True),
    sa.Column('watered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plot_contents'], ['plantings.planting_id'], ),
    sa.ForeignKeyConstraint(['plot_owner'], ['growers.grower_name'], ),
    sa.PrimaryKeyConstraint('grid_value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plots')
    op.drop_table('plantings')
    op.drop_table('growers')
    op.drop_table('crops')
    # ### end Alembic commands ###
